tap "homebrew/bundle"
tap "homebrew/core"

tap "homebrew/cask"
cask_args appdir: "/Applications"
cask "keycastr"

brew "autoconf"
brew "bash"
brew "bison"
brew "gcc"
brew "gdb"
brew "git"
brew "hugo"
brew "jq"
brew "make"
brew "peco"
brew "sbt"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "vim"
brew "zsh"
brew "anyenv"
tap "superbrothers/zsh-kubectl-prompt"
brew "zsh-kubectl-prompt"
brew "colordiff"
brew "zsh-syntax-highlighting"
brew "direnv"
